# ===================================
# 공통 설정 redirect-uri 배포용으로 바꾸면 됩니다
# ===================================
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile, email

          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET:vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbPLAINTEXT}

server:
  port: 8080

app:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost,http://localhost:5173}

payment:
  portone:
    imp-code: imp38147237
    api-key: 4607256811104714
    api-secret: z58ewwrg9BBTHYZZtKIIR6IH8nqjqarA5J9kgcrdgAJxeWYGjC7S1nQ4AyHExUeuoG8o4UoJQtFevkgL
    callback-url: http://localhost:8080/api/payments/portone/callback

# ===================================
# 로컬 환경
# ===================================
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1111}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

file:
  upload:
    directory: ./uploads

# ===================================
# 프로덕션 환경
# ===================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

file:
  upload:
    directory: ${FILE_UPLOAD_DIRECTORY:/uploads}

#spring:
#  profiles:
#    group:
#      local:
#        - common
#      prod:
#        - common
#  config:
#    activate:
#      on-profile: common
#
## 공통 설정
#---
#spring:
#  config:
#    activate:
#      on-profile: common
#jwt:
#  secret: ${JWT_SECRET:vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbPLAINTEXT}
#
#server:
#  port: 8080
#
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          client-id: ${GOOGLE_CLIENT_ID}
#          client-secret: ${GOOGLE_CLIENT_SECRET}
#          scope: profile, email
#        naver:
#          client-id: ${NAVER_CLIENT_ID}
#          client-secret: ${NAVER_CLIENT_SECRET}
#          authorization-grant-type: authorization_code
#          client-name: Naver
#          scope: name, email
#        kakao:
#          client-id: ${KAKAO_CLIENT_ID}
#          client-secret: ${KAKAO_CLIENT_SECRET}
#          client-name: Kakao
#          authorization-grant-type: authorization_code
#          client-authentication-method: client_secret_post
#          scope:
#            - profile_nickname
#            - account_email
#      provider:
#        naver:
#          authorization-uri: https://nid.naver.com/oauth2.0/authorize
#          token-uri: https://nid.naver.com/oauth2.0/token
#          user-info-uri: https://openapi.naver.com/v1/nid/me
#          user-name-attribute: response
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#          user-name-attribute: id
#
## 로컬 환경
#---
#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL:jdbc:mysql://localhost:3306/ddauction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:1111}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        jdbc:
#          time_zone: Asia/Seoul
#  jackson:
#    time-zone: Asia/Seoul
#
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          redirect-uri: http://localhost:8080/login/oauth2/code/google
#        naver:
#          redirect-uri: http://localhost:8080/login/oauth2/code/naver
#        kakao:
#          redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#
#app:
#  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost,http://localhost:5173}
#file:
#  upload:
#    directory: ${FILE_UPLOAD_DIRECTORY:./uploads}
#
## 배포 환경
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${RDS_ENDPOINT}:3306/ddauction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        jdbc:
#          time_zone: Asia/Seoul
#  jackson:
#    time-zone: Asia/Seoul
#
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          redirect-uri: https://your-production-domain.com/login/oauth2/code/google
#        naver:
#          redirect-uri: https://your-production-domain.com/login/oauth2/code/naver
#        kakao:
#          redirect-uri: https://your-production-domain.com/login/oauth2/code/kakao
#
#app:
#  allowed-origins: ${ALLOWED_ORIGINS}
#file:
#  upload:
#    directory: ${FILE_UPLOAD_DIRECTORY:/uploads}